//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Cruid.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Details
    {
        public int Product_Id { get; set; }
        public string barcode { get; set; }
        public string Product_Name { get; set; }
        public int Purchase_Prise { get; set; }
        public int Sales_Price { get; set; }
    }
}
